### ISSUE TITLE
How to run the example using windows?

### ISSUE THREAD

**Issue by ikhfa** [bpotard/idlak#4]
How to run the example using windows?

**Comment by bpotard** [comment]
I have never tried. Are you running cygwin to build things? The example will never run without cygwin or maybe minGw.

If I find a windows machine I'll try to give it a try, but I would really recommend trying it on a linux machine instead. I know that kaldi has always been very hard to run.

**Comment by ikhfa** [comment]
Ok, thanks. I've move on to linux (ubuntu 14.04). There are several errors when running the test. I'll open new issue.
