### ISSUE TITLE
Old IRSTLM doesn't compile on modern versions of gcc

### ISSUE THREAD

**Issue by danijel3** [bpotard/idlak#9]
The old version of IRSTLM causes compiler errors on gcc version 6.

Kaldi moved away from IRSTLM for that reason.

Suggest either using newer versions of IRSTLM from github, or switching to PocoLM, like the new versions of Kaldi.

**Comment by bpotard** [comment]
Hi,

Thanks, this is a known issue. The plan is to keep idlak in sync with kaldi, but we have not had time to upgrade to a recent version of the trunk while preserving all the functionalities of idlak yet. We will close that issue when this is done.

Blaise
